### ISSUE TITLE
No find precursor.cfg

### ISSUE THREAD

**Issue by folykkkkk** [srest2021/atlaslc#4]
I cannot find the file **_precursor.cfg_** from atlaslc. If it's convenient, could you please upload a copy? atlaslc is a very useful tool for me, and I would be very grateful if I can use it smoothly!

**Comment by srest2021** [comment]
Hi, the precursor.cfg file was renamed to settings.ini, but the README was never updated! If you want to use atlaslc, use settings.ini instead. 

Also, I just want to let you know that this repo is outdated and not currently maintained--I would recommend you use my atlaslc_jupyter repo, as it has clearer documentation and up-to-date code.

I hope this helps and let me know if you have any other questions!

**Comment by folykkkkk** [comment]
Thank you so much
